// src/components/Header.tsx
import React from 'react';

const Header = () => {
  return (
    <header>
      <h1>Website Title</h1>
      <nav>
        <ul>
          <li><a href="#home">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#services">Services</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>
      </nav>
      <style jsx>{`
        header {
          background: #f8f9fa;
          padding: 20px;
          text-align: center;
        }
        nav ul {
          list-style-type: none;
          padding: 0;
        }
        nav ul li {
          display: inline;
          margin: 0 15px;
        }
        nav ul li a {
          text-decoration: none;
          color: #0070f3;
        }
      `}</style>
    </header>
  );
};

export default Header;

// src/components/Header.vue
<template>
  <header>
    <h1>Header Component</h1>
    <nav>
      <ul>
        <li><router-link to="/home">Home</router-link></li>
        <li><router-link to="/about">About</router-link></li>
        <li><router-link to="/contact">Contact</router-link></li>
      </ul>
    </nav>
  </header>
</template>

<script>
export default {
  name: 'Header'
};
</script>

<style scoped>
header {
  background-color: #f8f9fa;
  padding: 1rem;
}
nav ul {
  list-style-type: none;
  padding: 0;
}
nav ul li {
  display: inline;
  margin-right: 1rem;
}
</style>
